version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: debug
    depends_on:
      prisma-db:
        condition: service_healthy
  prisma-db:
    container_name: prisma-db
    image: postgres:12
    ports:
      - "5403:5432"
    volumes:
      - prisma-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d prisma"]
      interval: 5s
      timeout: 5s
      retries: 5
  prisma-test-db:
    container_name: prisma-test-db
    image: postgres:12
    ports:
      - "5402:5432"
    volumes:
      - prisma-test-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma2020
      POSTGRES_DB: prisma
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"

volumes:
  prisma-store:
    driver: local
  prisma-test-store:
    driver: local
